### ISSUE TITLE
Does the program scrape the following information?

### ISSUE THREAD

**Issue by FraneCal** [Ashish-Github193/IndiaMart-Scraper#1]
Hello,

Does you program scrape the following information about the suppliers:

Name
product
city
address
contact person

Thank you.

**Comment by Ashish-Github193** [comment]
IndiaMart Scraping Keys:
1. gstin
2. company_name
3. page_link
4. address
5. state
6. zip_code
7. owner_name
8. phone_number
9. products
10. nature_of_business
11. annual_turnover

Owner Details (requires Apollo API key):
1. linkedin_url
2. personal_email
3. phone_number

Company Details  (requires Apollo API key):
1. founded_year
2. estimated_num_employees
3. industry
4. website_url
